"""ogviz — publication figure primitives shared across projects.

Import what you need from the top level; the submodules are the implementation.

    from ogviz import group_violins, save, titled, use_house_style

Group colours are NOT defined here. A project owns the meaning of its groups, so it passes
colours in. What ogviz owns is everything that should never differ between projects: the
canvas and type, the violin's stacking order, how a jittered point finds its x, where a
significance star sits relative to its bracket, and how a figure is written to disk.
"""

from importlib.metadata import PackageNotFoundError, version

from ogviz.guard import guard, guard_from_environment, guarded, is_guarded, unguard
from ogviz.layout import (
    annotate_clear,
    assert_no_text_overlap,
    assert_nothing_clipped,
    baseline,
    caption,
    clear_position,
    clipped_artists,
    dead_space,
    figure_margins,
    fit_under_header,
    grid_warnings,
    hairline_grid,
    label_rows,
    legend_pill,
    overflowing_text,
    panel_grid,
    panel_row,
    pill_frame,
    place_end_labels,
    required_margins,
    room_below,
    round_ticks,
    rows_that_fit,
    save,
    stack_without_overlap,
    text_over_data,
    text_overlaps,
    text_width_points,
    ticks_over_data,
    titled,
    trim_margins,
    value_ticks,
    width_for_bars,
    wrap_to_panel,
    wrap_to_width,
    zero_baseline,
)
from ogviz.marks import (
    Z_ERROR,
    Z_IQR,
    Z_MEAN_LINE,
    Z_MEDIAN_DOT,
    Z_POINTS,
    Z_VIOLIN,
    error_bars,
    iqr_box,
    jitter_x,
    mean_line,
    points,
    violin,
)
from ogviz.panels import (
    Cell,
    Cloud,
    Estimate,
    Leg,
    Line,
    Row,
    Series,
    Strand,
    align_brackets,
    align_mean_rows,
    align_ticks,
    bar_panel,
    benjamini_hochberg_rank,
    bonferroni_threshold,
    broken_zero,
    coupling_panels,
    crowded_ends,
    diverging_map,
    effect_heatmap,
    estimate_strip,
    group_violins,
    label_shared_scale_once,
    line_panel,
    money_ticks,
    multiplicity_ladder,
    null_distance,
    printed_means,
    reference_line,
    scatter_panel,
    series_colors,
    share_value_limits,
    shared_limits,
    slopegraph,
    split_violins,
    table_panel,
    tint,
    trend_line,
    value_floor,
    value_labels,
)
from ogviz.qc import assert_clean, audit
from ogviz.significance import bracket_stack, significance_row, spaced_stars, stars
from ogviz.tags import Tag, mark, marked, value_of
from ogviz.theme import (
    BAD,
    CANVAS,
    GLYPH_FAMILY,
    GOOD,
    GRID,
    INK,
    MUTED_INK,
    NO,
    PANEL_FILL,
    PAPER_WHITE,
    REFERENCE,
    SERIES,
    WARM_CANVAS,
    YES,
    family_for,
    glyphs_must_render,
    house_style,
    page_color,
    use_house_ink,
    use_house_style,
    use_house_type,
    use_reproducible_svg,
)

try:  # a project pins this so an ogviz change cannot silently alter a frozen figure
    __version__ = version("ogviz")
except PackageNotFoundError:  # running from a source tree that was never installed
    __version__ = "0+unknown"

__all__ = [
    "BAD",
    "CANVAS",
    "GLYPH_FAMILY",
    "GOOD",
    "GRID",
    "INK",
    "MUTED_INK",
    "NO",
    "PANEL_FILL",
    "PAPER_WHITE",
    "REFERENCE",
    "SERIES",
    "WARM_CANVAS",
    "YES",
    "Z_ERROR",
    "Z_IQR",
    "Z_MEAN_LINE",
    "Z_MEDIAN_DOT",
    "Z_POINTS",
    "Z_VIOLIN",
    "Cell",
    "Cloud",
    "Estimate",
    "Leg",
    "Line",
    "Row",
    "Series",
    "Strand",
    "Tag",
    "__version__",
    "align_brackets",
    "align_mean_rows",
    "align_ticks",
    "annotate_clear",
    "assert_clean",
    "assert_no_text_overlap",
    "assert_nothing_clipped",
    "audit",
    "bar_panel",
    "baseline",
    "benjamini_hochberg_rank",
    "bonferroni_threshold",
    "bracket_stack",
    "broken_zero",
    "caption",
    "clear_position",
    "clipped_artists",
    "coupling_panels",
    "crowded_ends",
    "dead_space",
    "diverging_map",
    "effect_heatmap",
    "error_bars",
    "estimate_strip",
    "family_for",
    "figure_margins",
    "fit_under_header",
    "glyphs_must_render",
    "grid_warnings",
    "group_violins",
    "guard",
    "guarded",
    "hairline_grid",
    "house_style",
    "iqr_box",
    "is_guarded",
    "jitter_x",
    "label_rows",
    "label_shared_scale_once",
    "legend_pill",
    "line_panel",
    "mark",
    "marked",
    "mean_line",
    "money_ticks",
    "multiplicity_ladder",
    "null_distance",
    "overflowing_text",
    "page_color",
    "panel_grid",
    "panel_row",
    "pill_frame",
    "place_end_labels",
    "points",
    "printed_means",
    "reference_line",
    "required_margins",
    "room_below",
    "round_ticks",
    "rows_that_fit",
    "save",
    "scatter_panel",
    "series_colors",
    "share_value_limits",
    "shared_limits",
    "significance_row",
    "slopegraph",
    "spaced_stars",
    "split_violins",
    "stack_without_overlap",
    "stars",
    "table_panel",
    "text_over_data",
    "text_overlaps",
    "text_width_points",
    "ticks_over_data",
    "tint",
    "titled",
    "trend_line",
    "trim_margins",
    "unguard",
    "use_house_ink",
    "use_house_style",
    "use_house_type",
    "use_reproducible_svg",
    "value_floor",
    "value_labels",
    "value_of",
    "value_ticks",
    "violin",
    "width_for_bars",
    "wrap_to_panel",
    "wrap_to_width",
    "zero_baseline",
]


# Off unless a project asks. See `ogviz.guard` for why a bare import must not change how matplotlib
# behaves, and why an environment variable is the right place for a project to decide once.
_GUARDING = guard_from_environment()
