"""Invented groups, so every example runs on a clean clone and shows nobody's data.

Fixed seeds: the gallery is regenerated by CI and by `just figures`, and an image that changes on
every run is a diff nobody can read. The shapes are chosen to exercise the awkward cases — a
skewed group, a small group beside a large one, values that need three decimals, values that need
a thousands separator.

The PARAMETERS are round and arbitrary on purpose. Drawing a synthetic sample is not enough: an
earlier version of this file seeded its generators with a real study's group means and real group
sizes, which puts that study's unpublished result in a public repository however synthetic the
individual points are. Nothing here should be recoverable as anyone's finding — if a number looks
plausibly like a measurement, that is the bug.
"""

from __future__ import annotations

import numpy as np

# Two groups with an intrinsic meaning, so the example passes colours in the way a project does.
TREATED = "#7C9A6E"
TREATED_EDGE = "#4A6136"
CONTROL = "#E8A838"
CONTROL_EDGE = "#B97C10"


def two_groups(seed: int = 0) -> dict[str, np.ndarray]:
    """A moderate separation with unequal n — the ordinary case."""
    rng = np.random.default_rng(seed)
    return {
        "control": rng.normal(0.0, 1.0, 40),
        "treated": rng.normal(-1.0, 1.2, 55),
    }


def concentration_ppm(seed: int = 5) -> dict[str, np.ndarray]:
    """Stored in ppm the way an instrument emits it, and read in ppb by everyone who uses it.

    This is the case display_scale exists for: without it the axis says "ppb" and carries
    -0.002, and a printed mean reads "-0.00".
    """
    rng = np.random.default_rng(seed)
    return {
        "control": rng.normal(2.0e-3, 0.5e-3, 40),
        "treated": rng.normal(3.5e-3, 0.6e-3, 55),
    }


def skewed_groups(seed: int = 1) -> dict[str, np.ndarray]:
    """One long tail, to show the violin doing something a box plot cannot."""
    rng = np.random.default_rng(seed)
    return {
        "control": rng.gamma(2.0, 0.6, 30) + 1.0,
        "treated": rng.gamma(6.0, 0.4, 44) + 1.0,
    }


def large_magnitudes(seed: int = 2) -> dict[str, np.ndarray]:
    """Values that need a thousands separator, like a relaxation time in milliseconds."""
    rng = np.random.default_rng(seed)
    return {"control": rng.normal(500, 40, 40), "treated": rng.normal(560, 45, 55)}


DOMAINS = ("fatigue", "sleep", "pain", "cognition", "autonomic")


def domain_profile(seed: int = 3) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Mean and standard error per domain per group — signed, so labels must be sign-aware."""
    rng = np.random.default_rng(seed)
    return {
        "control": (rng.normal(-0.5, 0.1, len(DOMAINS)), np.full(len(DOMAINS), 0.1)),
        "treated": (rng.normal(0.5, 0.1, len(DOMAINS)), np.full(len(DOMAINS), 0.1)),
    }


ARMS = ("frozen", "probe", "partial", "full")


def arm_scores(seed: int = 4) -> tuple[np.ndarray, np.ndarray]:
    """A monotone series with an asymmetric CI, and a ceiling to compare against."""
    rng = np.random.default_rng(seed)
    means = np.array([0.30, 0.45, 0.60, 0.70]) + rng.normal(0, 0.005, 4)
    errors = np.array([[0.05, 0.04, 0.04, 0.03], [0.06, 0.05, 0.04, 0.03]])
    return means, errors


def paired_sensors(seed: int = 6) -> tuple[list[np.ndarray], list[np.ndarray]]:
    """The same quantity measured two ways per category — the split-violin case.

    Nearly identical on purpose: the point of a shared spine is that a pair which agrees LOOKS
    like it agrees, where side-by-side violins leave a gap the eye reads as a difference.
    """
    rng = np.random.default_rng(seed)
    centres = (700.0, 760.0, 690.0, 700.0, 755.0, 685.0)
    first = [rng.normal(c, 45, 220) for c in centres]
    second = [a + rng.normal(0.0, 3.0, a.size) for a in first]
    return first, second


BLOCKS = ("B1", "B2", "B3", "B4", "B5", "B6")
ARM_LABELS = ("baseline", "variant A", "variant B", "variant C")


def headline_arms(seed: int = 7) -> tuple[np.ndarray, np.ndarray]:
    """Four arms scored on two metrics, with CI half-widths — the headline-bar case."""
    rng = np.random.default_rng(seed)
    first = np.array([0.34, 0.47, 0.58, 0.64]) + rng.normal(0, 0.004, 4)
    second = first - 0.09 + rng.normal(0, 0.004, 4)
    return first, second


COUPLING_VARIABLES = ("Marker (ppb)", "Mass index", "Burden score (z)")


def coupled_variables(seed: int = 8) -> dict[str, dict[str, np.ndarray]]:
    """Three variables on two groups, made to disagree pooled versus within.

    The groups sit apart on every axis while barely trending inside themselves, which is the
    arrangement a coupling figure exists to expose: pool them and the correlation is strong, look
    within either one and it nearly vanishes. Made-up numbers on made-up scales.
    """
    rng = np.random.default_rng(seed)
    out: dict[str, dict[str, np.ndarray]] = {}
    for name, size, offset in (("control", 40, 0.0), ("treated", 60, 2.0)):
        shared = rng.normal(0.0, 1.0, size)
        out[name] = {
            "marker": offset + 0.35 * shared + rng.normal(0.0, 1.0, size),
            "mass": offset + 0.35 * shared + rng.normal(0.0, 1.0, size),
            "burden": offset + 0.35 * shared + rng.normal(0.0, 1.0, size),
        }
    return out


def _spearman(x: np.ndarray, y: np.ndarray) -> float:
    """Pearson on the ranks. Written out so the examples need no statistics dependency."""
    rank_x = np.argsort(np.argsort(x)).astype(float)
    rank_y = np.argsort(np.argsort(y)).astype(float)
    centred_x, centred_y = rank_x - rank_x.mean(), rank_y - rank_y.mean()
    denominator = np.sqrt((centred_x**2).sum() * (centred_y**2).sum())
    return float((centred_x * centred_y).sum() / denominator) if denominator else 0.0


def correlation_with_interval(
    x: np.ndarray, y: np.ndarray, *, draws: int = 2000, seed: int = 9
) -> tuple[float, tuple[float, float], float]:
    """A rank correlation, a percentile bootstrap interval, and a permutation p.

    Statistics belong to the caller — ogviz places marks at numbers, it does not produce them.
    This is here so the example is runnable, not because it is the estimator anyone should use.
    """
    rng = np.random.default_rng(seed)
    estimate = _spearman(x, y)
    indices = rng.integers(0, x.size, size=(draws, x.size))
    resampled = np.array([_spearman(x[take], y[take]) for take in indices])
    low, high = (float(v) for v in np.percentile(resampled, [2.5, 97.5]))
    shuffled = np.array([_spearman(x, rng.permutation(y)) for _ in range(draws)])
    p = float((np.count_nonzero(np.abs(shuffled) >= abs(estimate)) + 1) / (draws + 1))
    return estimate, (min(low, estimate), max(high, estimate)), p


REGION_NAMES = ("Region A", "Region B", "Region C", "Region D")


def region_panels(seed: int = 11) -> dict[str, tuple[np.ndarray, np.ndarray, float]]:
    """Four regions measured in two groups, with a p for each — the one-panel-per-region case.

    The effects run from clear to absent on purpose. A grid where every panel tells the same story
    does not test anything: the interesting question is whether four panels drawn to one scale
    still let a reader see which region moved.
    """
    rng = np.random.default_rng(seed)
    separations = (-1.10, -0.72, -0.35, 0.04)
    p_values = (0.0004, 0.008, 0.06, 0.71)
    out: dict[str, tuple[np.ndarray, np.ndarray, float]] = {}
    for name, shift, p in zip(REGION_NAMES, separations, p_values, strict=True):
        out[name] = (
            rng.normal(0.0, 1.0, 38),
            rng.normal(shift, 1.05, 52),
            p,
        )
    return out


EFFORT_COST = (0.25, 0.35, 0.70, 1.30, 2.00, 2.60)


def effort_ladders(seed: int = 12) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Score against cost for four systems, each measured at a few effort settings.

    Not a sampled curve — five or six measured points per system, which is why the marks matter as
    much as the line joining them.
    """
    rng = np.random.default_rng(seed)
    cost = np.array(EFFORT_COST)
    ladders = {
        "System A": (cost, np.array([56.1, 58.0, 61.3, 63.2, 64.8, 64.7])),
        "System B": (cost[2:], np.array([58.2, 61.4, 61.8, 63.1])),
        "System C": (cost[1:5], np.array([50.2, 55.2, 55.7, 57.6])),
        "Baseline": (cost, np.array([40.0, 44.0, 47.0, 49.0, 50.2, 50.5])),
    }
    return {name: (x, y + rng.normal(0.0, 0.05, y.size)) for name, (x, y) in ladders.items()}


NATIONS = ("Air Nomads", "Water Tribe", "Earth Kingdom", "Fire Nation")


def bending_by_nation(seed: int = 13) -> dict[str, tuple[np.ndarray, np.ndarray, float]]:
    """Novice against master benders in each of the four nations. Entirely invented.

    Four panels of the same comparison at different strengths, which is what a grid is for: the
    Air Nomads separate cleanly, the Fire Nation barely at all.
    """
    rng = np.random.default_rng(seed)
    separations = (1.35, 0.95, 0.55, 0.12)
    p_values = (0.0002, 0.006, 0.05, 0.68)
    return {
        nation: (
            rng.normal(0.0, 1.0, 36),
            rng.normal(shift, 1.05, 48),
            p,
        )
        for nation, shift, p in zip(NATIONS, separations, p_values, strict=True)
    }


FORMATIONS = ("4-2-3-1", "3-4-3", "4-3-3", "3-5-2")
LEAGUE_AVERAGE_XG = 1.42


def expected_goals(seed: int = 14) -> tuple[np.ndarray, np.ndarray]:
    """Invented expected-goals-per-match by formation, with an asymmetric interval.

    Made-up numbers on a real quantity's scale. No season, no opponent and no player is named,
    because a fake statistic sitting beside a real name reads as a claim about that name.
    """
    rng = np.random.default_rng(seed)
    means = np.array([1.18, 1.36, 1.61, 1.74]) + rng.normal(0.0, 0.01, 4)
    errors = np.array([[0.16, 0.14, 0.13, 0.11], [0.19, 0.17, 0.15, 0.13]])
    return means, errors
