"""Invented groups, so every example runs on a clean clone and shows nobody's data.

Fixed seeds: the gallery is regenerated by CI and by `just figures`, and an image that changes on
every run is a diff nobody can read. The shapes are chosen to exercise the awkward cases — a
skewed group, a small group beside a large one, values that need three decimals, values that need
a thousands separator.

The PARAMETERS are round and arbitrary on purpose. Drawing a synthetic sample is not enough: an
earlier version of this file seeded its generators with a real study's group means and real group
sizes, which puts that study's unpublished result in a public repository however synthetic the
individual points are. Nothing here should be recoverable as anyone's finding — if a number looks
plausibly like a measurement, that is the bug.
"""

from __future__ import annotations

import numpy as np

# Two groups with an intrinsic meaning, so the example passes colours in the way a project does.
TREATED = "#7C9A6E"
TREATED_EDGE = "#4A6136"
CONTROL = "#E8A838"
CONTROL_EDGE = "#B97C10"

# THREE conditions — amber, blue, green — for the two condition grids. Saturated rather than pastel
# and drawn at a low alpha, so the body is pale but its outline is not: the dots sit ON the body,
# and a fill strong enough to be seen behind forty dots is strong enough to compete with them.
#
# MEASURED, because the pair to watch is not the obvious one: amber against green is the widest gap
# to normal vision and the tightest under protanopia (0.699 -> 0.302), while blue against green is
# comfortable everywhere except tritanopia, where `ogviz.color.separation` puts it at 0.043 — one
# colour. `indistinguishable_series` reports that pair, and it is kept anyway for a reason the
# check cannot see: on a condition grid every violin sits over its own labelled tick, so nothing is
# identified by colour alone and the labels survive any deficiency. Put these three in a LEGEND and
# the finding applies in full.
CONDITION_TINTS = ("#E8B33C", "#5B9BD5", "#3FA372")

# The standard heart-rate-variability bands, and the tone each is shaded in. VLF is deliberately
# NOT shaded: three adjacent regions read as one grey block, and it is the band everyone reports
# and nobody interprets.
SPECTRAL_BANDS = (("LF", 0.04, 0.15, "#B9860B"), ("HF", 0.15, 0.40, "#2E7D5B"))


def heart_rate_spectra(seed: int = 3) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    """Invented spectra with the SHAPE a heart-rate spectrum actually has. Nobody's data.

    A pure power law is a straight line on log-log, and a straight line is what a spectrum looks
    like when it has been invented by someone who has not seen one. A real spectrum BENDS: flat
    below a knee, falling above it. So the background here is `1 / (1 + (f/knee)**chi)`, the form a
    bounded stochastic process gives and the one FOOOF fits as its knee model.

    On top of that sit the two peaks that make it physiology rather than a slope — the Mayer wave
    near 0.1 Hz and the respiratory peak near 0.25. The conditions move them in OPPOSITE
    directions, which is the reading the figure exists to show: the task trades HF for LF, and the
    recovery overshoots the baseline in HF rather than merely returning to it.

    Every subject gets their own overall level, their own knee and their own peak frequencies,
    because a between-subject interval computed from spectra that differ only by noise is an
    interval about nothing.
    """
    rng = np.random.default_rng(seed)
    frequencies = np.logspace(np.log10(0.003), np.log10(0.5), 260)
    # (knee Hz, chi, LF gain, LF centre, HF gain, HF centre, HF width)
    settings = {
        "Baseline": (0.022, 1.9, 2.4, 0.098, 3.0, 0.245, 0.085),
        "Task": (0.026, 2.1, 5.2, 0.105, 0.9, 0.290, 0.070),
        "Recovery": (0.020, 1.8, 1.9, 0.092, 4.4, 0.235, 0.100),
    }
    spectra = {}
    for name, (knee, chi, lf_gain, lf_at, hf_gain, hf_at, hf_width) in settings.items():
        rows = []
        for _ in range(COHORT):
            level = 10 ** (2.55 + rng.normal(0.0, 0.13))
            background = level / (1.0 + (frequencies / (knee * rng.uniform(0.9, 1.1))) ** chi)
            low = lf_gain * rng.uniform(0.7, 1.3) * _bump(frequencies, lf_at, 0.075, rng)
            high = hf_gain * rng.uniform(0.6, 1.4) * _bump(frequencies, hf_at, hf_width / 2.2, rng)
            wobble = rng.normal(0.0, 0.045, frequencies.size)
            rows.append(background * (1 + low + high) * 10**wobble)
        spectra[name] = np.array(rows)
    return frequencies, spectra


def _bump(frequencies: np.ndarray, centre: float, width: float, rng: np.random.Generator):
    """A Gaussian in LOG frequency — a peak is a constant fraction of its centre, not of a Hz."""
    moved = centre * rng.uniform(0.94, 1.06)  # this subject's own peak frequency
    return np.exp(-((np.log10(frequencies) - np.log10(moved)) ** 2) / (2 * width**2))


def two_groups(seed: int = 0) -> dict[str, np.ndarray]:
    """A moderate separation with unequal n — the ordinary case."""
    rng = np.random.default_rng(seed)
    return {
        "control": rng.normal(0.0, 1.0, 40),
        "treated": rng.normal(-1.0, 1.2, 55),
    }


def concentration_ppm(seed: int = 5) -> dict[str, np.ndarray]:
    """Stored in ppm the way an instrument emits it, and read in ppb by everyone who uses it.

    This is the case display_scale exists for: without it the axis says "ppb" and carries
    -0.002, and a printed mean reads "-0.00".
    """
    rng = np.random.default_rng(seed)
    return {
        "control": rng.normal(2.0e-3, 0.5e-3, 40),
        "treated": rng.normal(3.5e-3, 0.6e-3, 55),
    }


def skewed_groups(seed: int = 1) -> dict[str, np.ndarray]:
    """One long tail, to show the violin doing something a box plot cannot."""
    rng = np.random.default_rng(seed)
    return {
        "control": rng.gamma(2.0, 0.6, 30) + 1.0,
        "treated": rng.gamma(6.0, 0.4, 44) + 1.0,
    }


def large_magnitudes(seed: int = 2) -> dict[str, np.ndarray]:
    """Values that need a thousands separator, like a relaxation time in milliseconds."""
    rng = np.random.default_rng(seed)
    return {"control": rng.normal(500, 40, 40), "treated": rng.normal(560, 45, 55)}


DOMAINS = ("fatigue", "sleep", "pain", "cognition", "autonomic")


def domain_profile(seed: int = 3) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Mean and standard error per domain per group — signed, so labels must be sign-aware."""
    rng = np.random.default_rng(seed)
    return {
        "control": (rng.normal(-0.5, 0.1, len(DOMAINS)), np.full(len(DOMAINS), 0.1)),
        "treated": (rng.normal(0.5, 0.1, len(DOMAINS)), np.full(len(DOMAINS), 0.1)),
    }


def paired_sensors(seed: int = 6) -> tuple[list[np.ndarray], list[np.ndarray]]:
    """The same quantity measured two ways per category — the split-violin case.

    Nearly identical on purpose: the point of a shared spine is that a pair which agrees LOOKS
    like it agrees, where side-by-side violins leave a gap the eye reads as a difference.
    """
    rng = np.random.default_rng(seed)
    centres = (700.0, 760.0, 690.0, 700.0, 755.0, 685.0)
    first = [rng.normal(c, 45, 220) for c in centres]
    second = [a + rng.normal(0.0, 3.0, a.size) for a in first]
    return first, second


BLOCKS = ("B1", "B2", "B3", "B4", "B5", "B6")
ARM_LABELS = ("baseline", "variant A", "variant B", "variant C")


def coupled_variables(seed: int = 8) -> dict[str, dict[str, np.ndarray]]:
    """Three variables on two groups, made to disagree pooled versus within.

    The groups sit apart on every axis while barely trending inside themselves, which is the
    arrangement a coupling figure exists to expose: pool them and the correlation is strong, look
    within either one and it nearly vanishes. Made-up numbers on made-up scales.
    """
    rng = np.random.default_rng(seed)
    out: dict[str, dict[str, np.ndarray]] = {}
    for name, size, offset in (("control", 40, 0.0), ("treated", 60, 2.0)):
        shared = rng.normal(0.0, 1.0, size)
        out[name] = {
            "marker": offset + 0.35 * shared + rng.normal(0.0, 1.0, size),
            "mass": offset + 0.35 * shared + rng.normal(0.0, 1.0, size),
            "burden": offset + 0.35 * shared + rng.normal(0.0, 1.0, size),
        }
    return out


def _spearman(x: np.ndarray, y: np.ndarray) -> float:
    """Pearson on the ranks. Written out so the examples need no statistics dependency."""
    rank_x = np.argsort(np.argsort(x)).astype(float)
    rank_y = np.argsort(np.argsort(y)).astype(float)
    centred_x, centred_y = rank_x - rank_x.mean(), rank_y - rank_y.mean()
    denominator = np.sqrt((centred_x**2).sum() * (centred_y**2).sum())
    return float((centred_x * centred_y).sum() / denominator) if denominator else 0.0


def correlation_with_interval(
    x: np.ndarray, y: np.ndarray, *, draws: int = 2000, seed: int = 9
) -> tuple[float, tuple[float, float], float]:
    """A rank correlation, a percentile bootstrap interval, and a permutation p.

    Statistics belong to the caller — ogviz places marks at numbers, it does not produce them.
    This is here so the example is runnable, not because it is the estimator anyone should use.
    """
    rng = np.random.default_rng(seed)
    estimate = _spearman(x, y)
    indices = rng.integers(0, x.size, size=(draws, x.size))
    resampled = np.array([_spearman(x[take], y[take]) for take in indices])
    low, high = (float(v) for v in np.percentile(resampled, [2.5, 97.5]))
    shuffled = np.array([_spearman(x, rng.permutation(y)) for _ in range(draws)])
    p = float((np.count_nonzero(np.abs(shuffled) >= abs(estimate)) + 1) / (draws + 1))
    # The interval is widened to contain the estimate if it does not already, because `Estimate`
    # refuses a dot outside its own bar. That is a real thing a percentile bootstrap can do on a
    # skewed statistic, and widening HIDES it — so it is written down here rather than left as a
    # `min`/`max` a reader would copy without noticing. On this file's data it never fires; checked
    # across all six pairs the gallery draws, the reported interval is the percentile one unchanged.
    # A project doing this for real should let the disagreement surface instead of smoothing it.
    return estimate, (min(low, estimate), max(high, estimate)), p


EFFORT_COST = (0.25, 0.35, 0.70, 1.30, 2.00, 2.60)


def effort_ladders(seed: int = 12) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Score against cost for four systems, each measured at a few effort settings.

    Not a sampled curve — five or six measured points per system, which is why the marks matter as
    much as the line joining them.
    """
    rng = np.random.default_rng(seed)
    cost = np.array(EFFORT_COST)
    ladders = {
        "System A": (cost, np.array([56.1, 58.0, 61.3, 63.2, 64.8, 64.7])),
        "System B": (cost[2:], np.array([58.2, 61.4, 61.8, 63.1])),
        "System C": (cost[1:5], np.array([50.2, 55.2, 55.7, 57.6])),
        "Baseline": (cost, np.array([40.0, 44.0, 47.0, 49.0, 50.2, 50.5])),
    }
    return {name: (x, y + rng.normal(0.0, 0.05, y.size)) for name, (x, y) in ladders.items()}


NATIONS = ("Air Nomads", "Water Tribe", "Earth Kingdom", "Fire Nation")
BENDING_LEVELS = ("Novice", "Adept", "Master")
# One cohort, measured under every condition in every panel — a REPEATED-MEASURES grid. The number
# is the length of every array these builders return, and the dots are drawn in this order, so a
# figure colouring by identity gets the same subject in the same colour everywhere by construction
# rather than by the caller keeping two lists in step.
COHORT = 26


def bending_by_nation(
    seed: int = 13,
) -> dict[str, tuple[dict[str, np.ndarray], tuple[tuple[str, str, float], ...]]]:
    """One cohort of benders at three levels of training, in each of the four nations. Invented.

    Four panels of the same three-way comparison at different strengths, which is what a grid is
    for: the Air Nomads separate cleanly, the Fire Nation barely at all.

    Every bender carries an OWN TALENT that follows them across the three levels, because that is
    what makes a repeated-measures panel worth drawing: a reader following one dot sees a subject
    who was strong as a novice still strong as a master. Drawing the three levels independently
    would give the same violins and the same p-values, and every dot would be a different person.
    """
    rng = np.random.default_rng(seed)
    gains = (1.35, 0.95, 0.55, 0.12)
    significance = (
        (("Novice", "Adept", 0.004), ("Adept", "Master", 0.03), ("Novice", "Master", 0.0002)),
        (("Novice", "Adept", 0.04), ("Adept", "Master", 0.09), ("Novice", "Master", 0.006)),
        (("Novice", "Adept", 0.21), ("Adept", "Master", 0.14), ("Novice", "Master", 0.05)),
        (("Novice", "Adept", 0.74), ("Adept", "Master", 0.58), ("Novice", "Master", 0.68)),
    )
    grid = {}
    for nation, gain, tests in zip(NATIONS, gains, significance, strict=True):
        talent = rng.normal(0.0, 0.72, COHORT)
        grid[nation] = (
            {
                level: talent + step * gain + rng.normal(0.0, 0.74, COHORT)
                for level, step in zip(BENDING_LEVELS, (0.0, 0.5, 1.0), strict=True)
            },
            tests,
        )
    return grid


FORMATIONS = ("4-2-3-1", "3-4-3", "4-3-3", "3-5-2")
LEAGUE_AVERAGE_XG = 1.42


def expected_goals(seed: int = 14) -> tuple[np.ndarray, np.ndarray]:
    """Invented expected-goals-per-match by formation, with an asymmetric interval.

    Made-up numbers on a real quantity's scale. No season, no opponent and no player is named,
    because a fake statistic sitting beside a real name reads as a claim about that name.
    """
    rng = np.random.default_rng(seed)
    means = np.array([1.18, 1.36, 1.61, 1.74]) + rng.normal(0.0, 0.01, 4)
    errors = np.array([[0.16, 0.14, 0.13, 0.11], [0.19, 0.17, 0.15, 0.13]])
    return means, errors


STAGES_OF_THE_ROAD = ("The Shire", "The Road", "The Return")
# Six measures of one company at those three stages: title, unit, the three means, and the spread.
# The UNITS ARE DELIBERATELY UNLIKE EACH OTHER — a count, a weight, an hour, and one that runs into
# five figures — because that is the case a per-panel scale exists for. On one shared scale the
# steps would flatten every other panel into a line, and the panel that needs a thousands separator
# would never get to show it.
JOURNEY_MEASURES: tuple[tuple[str, str, tuple[float, float, float], float], ...] = (
    ("Second breakfasts", "per day", (2.4, 0.7, 1.9), 0.26),
    ("Pack weight", "kg", (11.0, 18.4, 8.6), 2.6),
    ("Steps walked", "per day", (6200.0, 21500.0, 7400.0), 1700.0),
    ("Sleep", "hours", (9.1, 5.3, 8.4), 1.05),
    ("Songs sung", "per day", (4.3, 1.2, 3.7), 0.95),
    ("Pipe-weed", "oz per week", (3.1, 1.4, 3.0), 0.42),
)


def journey_measures(
    seed: int = 15,
) -> dict[str, tuple[str, dict[str, np.ndarray], tuple[tuple[str, str, float], ...]]]:
    """One company, six measures, three stages of the road. Entirely invented.

    The shape a condition grid takes: the CONDITIONS are the same in every panel and the MEASURE
    changes, so the grid answers one question six ways rather than asking six questions. Every
    panel's comparison is therefore the same comparison, which is what lets a reader read down the
    column instead of re-orienting at each panel.

    The road is the hard stage in every measure and the return recovers most but not all of it,
    except the pipe-weed, which recovers all of it. A grid wants one panel that does not follow the
    pattern, or a reader learns the pattern from the first panel and stops looking.
    """
    rng = np.random.default_rng(seed)
    grid = {}
    for title, unit, means, spread in JOURNEY_MEASURES:
        # Each walker's own level, in units of the spread, carried across all three stages.
        walker = rng.normal(0.0, 0.68, COHORT)
        stages = {
            stage: mean + walker * spread + rng.normal(0.0, spread * 0.72, COHORT)
            for stage, mean in zip(STAGES_OF_THE_ROAD, means, strict=True)
        }
        recovered = abs(means[2] - means[0]) < spread * 0.25  # the pipe-weed panel
        grid[title] = (
            unit,
            stages,
            (
                ("The Shire", "The Road", 0.0004),
                ("The Road", "The Return", 0.002),
                ("The Shire", "The Return", 0.44 if recovered else 0.03),
            ),
        )
    return grid


TRIALS_OF_THE_TOURNAMENT = (
    "Sword swallowing",
    "Fire breathing",
    "Plate spinning",
    "Knife juggling",
    "Lion taming",
    "Tightrope",
    "Trapeze",
    "Escapology",
    "Contortion",
    "Human cannonball",
    "Card throwing",
    "Stilt walking",
    "Hoop diving",
    "Whip cracking",
    "Unicycling",
)


ACTS = ("Acrobatics", "Illusion", "Clowning", "Aerials", "Beasts", "Music")
JUDGES = ("Technique", "Danger", "Showmanship", "Costume")


def act_scores(seed: int = 17) -> tuple[np.ndarray, np.ndarray]:
    """Invented judge-by-act effects and their p-values, with one act unjudged on one criterion.

    The missing cell is on purpose: a matrix panel has to say "not measured" differently from
    "measured and zero", and an example with no gap in it never shows whether it does.
    """
    rng = np.random.default_rng(seed)
    effects = rng.normal(0.0, 0.55, (len(ACTS), len(JUDGES)))
    effects[0, 0] = 1.32
    effects[4, 1] = -1.18
    effects[2, 3] = np.nan
    p_values = rng.uniform(0.0, 0.4, (len(ACTS), len(JUDGES)))
    p_values[0, 0] = 0.0003
    p_values[4, 1] = 0.004
    return effects, p_values


ROUNDS = ("Heats", "Quarter", "Semi", "Final")


def scores_by_round(seed: int = 18) -> dict[str, tuple[list[float], list[tuple[float, float]]]]:
    """Invented per-round scores with a bootstrap-style band. Round numbers, no measurement."""
    del seed
    return {
        "Acrobatics": (
            [0.10, 0.32, 0.55, 0.78],
            [(0.02, 0.18), (0.22, 0.42), (0.44, 0.66), (0.66, 0.90)],
        ),
        "Illusion": (
            [0.20, 0.28, 0.30, 0.34],
            [(0.12, 0.28), (0.19, 0.37), (0.20, 0.40), (0.23, 0.45)],
        ),
        "Beasts": (
            [0.30, 0.18, 0.02, -0.14],
            [(0.22, 0.38), (0.09, 0.27), (-0.08, 0.12), (-0.26, -0.02)],
        ),
    }


# There were TWO module-level `ARMS` until 2026-08-07, and Python does not mind: the second simply
# won, so the first one's labels were unreachable and the helper paired with them drew nothing. An
# example added against the earlier meaning would have come out mislabelled with nothing raised —
# the same shape as a `highlight` index that stays valid and quietly starts meaning something else.
ARMS = ("From scratch", "Frozen probe", "Fine-tuned", "Reference")
ARM_COLORS = ("#ED6B3B", "#2E7CE0", "#2E7CE0", "#9B3B8F")


def arm_comparison(seed: int = 19) -> dict[str, tuple[list[float], list[tuple[float, float]]]]:
    """Two metrics per arm with an interval each. Invented, round, and nobody's result.

    Shaped like a controlled head-to-head: three arms that ARE comparable and one reference that is
    not, which is why the reference stands apart on the axis and outside the backdrop.
    """
    del seed
    return {
        "Coarse score": (
            [0.42, 0.61, 0.66, 0.70],
            [(0.38, 0.46), (0.57, 0.65), (0.62, 0.70), (0.66, 0.74)],
        ),
        "Fine score": (
            [0.30, 0.52, 0.58, 0.63],
            [(0.26, 0.34), (0.48, 0.56), (0.54, 0.62), (0.59, 0.67)],
        ),
    }


# A sample rate round enough to read off the axis, and low enough that the example renders quickly.
SAMPLE_RATE = 8000


def chirped_tone(seed: int = 14) -> tuple[np.ndarray, int]:
    """An invented signal with three things a spectrogram is supposed to show, and one it is not.

    A steady tone that STOPS partway through, a rising sweep that crosses it, and a broadband click.
    Between them they exercise the three readings a time-frequency figure is for: a horizontal line
    is a constant frequency, a diagonal is a changing one, a vertical is an instant containing every
    frequency at once. The noise floor is there so the decibel floor has something to do — with a
    silent background, any floor looks like the right floor.

    Returned with its sample rate, because a spectrogram's axes are meaningless without one and
    handing back a bare array is how the two get separated.
    """
    rng = np.random.default_rng(seed)
    duration = 2.0
    t = np.arange(0.0, duration, 1.0 / SAMPLE_RATE)

    tone = np.sin(2.0 * np.pi * 600.0 * t) * (t < 1.25)  # stops at 1.25 s

    # A linear chirp, from its PHASE. Written the obvious way — `sin(2*pi * linspace(f0, f1) * t)` —
    # the instantaneous frequency is the derivative of `f(t) * t`, which is `f0 + 2*(f1-f0)*t/T`:
    # it ends at 2*f1 - f0, not at f1. With f1 = 2600 that reaches 5000 Hz on an 8 kHz signal, past
    # the 4 kHz Nyquist limit, and the sweep FOLDS BACK down the spectrogram as a mirrored line.
    # It renders as a clean bright diagonal and is an artefact of the sampling, not the signal.
    # Caught by looking at the rendered figure, which is the only place it is visible.
    start, end = 200.0, 2600.0
    phase = 2.0 * np.pi * (start * t + 0.5 * (end - start) / duration * t**2)
    sweep = 0.6 * np.sin(phase)
    click = np.zeros_like(t)
    click[int(1.6 * SAMPLE_RATE) : int(1.6 * SAMPLE_RATE) + 12] = 3.0  # one broadband instant
    noise = 0.02 * rng.standard_normal(t.size)
    return tone + sweep + click + noise, SAMPLE_RATE


def short_time_spectrum(seed: int = 14) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """The signal above as (power in dB, times, frequencies) — a plain Hann-window STFT.

    The window and hop are stated here rather than defaulted anywhere in the package, because they
    decide what the picture means: a 256-sample window at 8 kHz is 32 ms, which resolves the sweep
    in time at the cost of frequency resolution, and the opposite choice would draw a different
    figure from the same signal. That trade is the caller's, always.
    """
    from scipy.signal import ShortTimeFFT
    from scipy.signal.windows import hann

    from ogviz import to_decibels

    signal, rate = chirped_tone(seed)
    window = hann(256, sym=False)
    transform = ShortTimeFFT(window, hop=64, fs=rate, scale_to="magnitude")
    power = np.abs(transform.stft(signal)) ** 2
    return to_decibels(power, floor_db=-70.0), transform.t(signal.size), transform.f


# One panel per metric, the same systems in every panel — the shape a benchmark table wants to be.
# `lower_is_better` is carried per metric rather than inferred, because nothing about a number says
# which direction is good, and a grid that guesses will bold the loser on the error metrics.
SYSTEMS = ("Baseline", "System A", "System B", "System C", "System D")
METRICS: tuple[tuple[str, str, bool], ...] = (
    ("Overlap", "area agreement", False),
    ("Detection", "items found at all", False),
    ("Recall", "of what is there", False),
    ("Precision", "of what is claimed", False),
    ("Stability", "across reruns", False),
    ("Agreement", "two raters", False),
    ("Boundary (mm)", "lower better", True),
    ("Volume error", "lower better", True),
)


def metric_grid(seed: int = 21) -> dict[str, tuple[np.ndarray, np.ndarray, bool, int]]:
    """Five systems scored on eight invented metrics, with a bootstrap-style interval each.

    Returns per metric: the values, the interval half-widths, whether lower wins, and which system
    won. The WINNER IS COMPUTED from the values and the direction, never passed in — a grid whose
    outline is set by hand goes wrong the first time a number changes, and it would go wrong
    silently, because a bold bar looks deliberate whichever one it is.

    No system wins everything, and the two error metrics are won by a different one than the six
    score metrics. That is the arrangement the figure exists for: read down a column and one system
    is not simply best, which a single headline number would have hidden.
    """
    rng = np.random.default_rng(seed)
    grid: dict[str, tuple[np.ndarray, np.ndarray, bool, int]] = {}
    scores = {
        "Overlap": (0.742, 0.681, 0.675, 0.669, 0.658),
        "Detection": (0.737, 0.724, 0.688, 0.671, 0.592),
        "Recall": (0.664, 0.731, 0.726, 0.690, 0.551),
        "Precision": (0.858, 0.744, 0.679, 0.702, 0.719),
        "Stability": (0.713, 0.727, 0.748, 0.741, 0.712),
        "Agreement": (0.812, 0.661, 0.642, 0.638, 0.651),
        "Boundary (mm)": (5.14, 4.32, 4.77, 5.09, 9.11),
        "Volume error": (0.244, 0.219, 0.272, 0.264, 0.269),
    }
    for name, _what, lower_is_better in METRICS:
        values = np.array(scores[name], dtype=float)
        spread = values * rng.uniform(0.035, 0.12, values.size)
        best = int(np.argmin(values) if lower_is_better else np.argmax(values))
        grid[name] = (values, spread, lower_is_better, best)
    return grid
