"""Invented groups, so every example runs on a clean clone and shows nobody's data.

Fixed seeds: the gallery is regenerated by CI and by `just figures`, and an image that changes on
every run is a diff nobody can read. The shapes are chosen to exercise the awkward cases — a
skewed group, a small group beside a large one, values that need three decimals, values that need
a thousands separator.

The PARAMETERS are round and arbitrary on purpose. Drawing a synthetic sample is not enough: an
earlier version of this file seeded its generators with a real study's group means and real group
sizes, which puts that study's unpublished result in a public repository however synthetic the
individual points are. Nothing here should be recoverable as anyone's finding — if a number looks
plausibly like a measurement, that is the bug.
"""

from __future__ import annotations

import numpy as np

# Two groups with an intrinsic meaning, so the example passes colours in the way a project does.
TREATED = "#7C9A6E"
TREATED_EDGE = "#4A6136"
CONTROL = "#E8A838"
CONTROL_EDGE = "#B97C10"


def two_groups(seed: int = 0) -> dict[str, np.ndarray]:
    """A moderate separation with unequal n — the ordinary case."""
    rng = np.random.default_rng(seed)
    return {
        "control": rng.normal(0.0, 1.0, 40),
        "treated": rng.normal(-1.0, 1.2, 55),
    }


def concentration_ppm(seed: int = 5) -> dict[str, np.ndarray]:
    """Stored in ppm the way an instrument emits it, and read in ppb by everyone who uses it.

    This is the case display_scale exists for: without it the axis says "ppb" and carries
    -0.002, and a printed mean reads "-0.00".
    """
    rng = np.random.default_rng(seed)
    return {
        "control": rng.normal(2.0e-3, 0.5e-3, 40),
        "treated": rng.normal(3.5e-3, 0.6e-3, 55),
    }


def skewed_groups(seed: int = 1) -> dict[str, np.ndarray]:
    """One long tail, to show the violin doing something a box plot cannot."""
    rng = np.random.default_rng(seed)
    return {
        "control": rng.gamma(2.0, 0.6, 30) + 1.0,
        "treated": rng.gamma(6.0, 0.4, 44) + 1.0,
    }


def large_magnitudes(seed: int = 2) -> dict[str, np.ndarray]:
    """Values that need a thousands separator, like a relaxation time in milliseconds."""
    rng = np.random.default_rng(seed)
    return {"control": rng.normal(500, 40, 40), "treated": rng.normal(560, 45, 55)}


DOMAINS = ("fatigue", "sleep", "pain", "cognition", "autonomic")


def domain_profile(seed: int = 3) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Mean and standard error per domain per group — signed, so labels must be sign-aware."""
    rng = np.random.default_rng(seed)
    return {
        "control": (rng.normal(-0.5, 0.1, len(DOMAINS)), np.full(len(DOMAINS), 0.1)),
        "treated": (rng.normal(0.5, 0.1, len(DOMAINS)), np.full(len(DOMAINS), 0.1)),
    }


def paired_sensors(seed: int = 6) -> tuple[list[np.ndarray], list[np.ndarray]]:
    """The same quantity measured two ways per category — the split-violin case.

    Nearly identical on purpose: the point of a shared spine is that a pair which agrees LOOKS
    like it agrees, where side-by-side violins leave a gap the eye reads as a difference.
    """
    rng = np.random.default_rng(seed)
    centres = (700.0, 760.0, 690.0, 700.0, 755.0, 685.0)
    first = [rng.normal(c, 45, 220) for c in centres]
    second = [a + rng.normal(0.0, 3.0, a.size) for a in first]
    return first, second


BLOCKS = ("B1", "B2", "B3", "B4", "B5", "B6")
ARM_LABELS = ("baseline", "variant A", "variant B", "variant C")


def headline_arms(seed: int = 7) -> tuple[np.ndarray, np.ndarray]:
    """Four arms scored on two metrics, with CI half-widths — the headline-bar case."""
    rng = np.random.default_rng(seed)
    first = np.array([0.34, 0.47, 0.58, 0.64]) + rng.normal(0, 0.004, 4)
    second = first - 0.09 + rng.normal(0, 0.004, 4)
    return first, second


def coupled_variables(seed: int = 8) -> dict[str, dict[str, np.ndarray]]:
    """Three variables on two groups, made to disagree pooled versus within.

    The groups sit apart on every axis while barely trending inside themselves, which is the
    arrangement a coupling figure exists to expose: pool them and the correlation is strong, look
    within either one and it nearly vanishes. Made-up numbers on made-up scales.
    """
    rng = np.random.default_rng(seed)
    out: dict[str, dict[str, np.ndarray]] = {}
    for name, size, offset in (("control", 40, 0.0), ("treated", 60, 2.0)):
        shared = rng.normal(0.0, 1.0, size)
        out[name] = {
            "marker": offset + 0.35 * shared + rng.normal(0.0, 1.0, size),
            "mass": offset + 0.35 * shared + rng.normal(0.0, 1.0, size),
            "burden": offset + 0.35 * shared + rng.normal(0.0, 1.0, size),
        }
    return out


def _spearman(x: np.ndarray, y: np.ndarray) -> float:
    """Pearson on the ranks. Written out so the examples need no statistics dependency."""
    rank_x = np.argsort(np.argsort(x)).astype(float)
    rank_y = np.argsort(np.argsort(y)).astype(float)
    centred_x, centred_y = rank_x - rank_x.mean(), rank_y - rank_y.mean()
    denominator = np.sqrt((centred_x**2).sum() * (centred_y**2).sum())
    return float((centred_x * centred_y).sum() / denominator) if denominator else 0.0


def correlation_with_interval(
    x: np.ndarray, y: np.ndarray, *, draws: int = 2000, seed: int = 9
) -> tuple[float, tuple[float, float], float]:
    """A rank correlation, a percentile bootstrap interval, and a permutation p.

    Statistics belong to the caller — ogviz places marks at numbers, it does not produce them.
    This is here so the example is runnable, not because it is the estimator anyone should use.
    """
    rng = np.random.default_rng(seed)
    estimate = _spearman(x, y)
    indices = rng.integers(0, x.size, size=(draws, x.size))
    resampled = np.array([_spearman(x[take], y[take]) for take in indices])
    low, high = (float(v) for v in np.percentile(resampled, [2.5, 97.5]))
    shuffled = np.array([_spearman(x, rng.permutation(y)) for _ in range(draws)])
    p = float((np.count_nonzero(np.abs(shuffled) >= abs(estimate)) + 1) / (draws + 1))
    # The interval is widened to contain the estimate if it does not already, because `Estimate`
    # refuses a dot outside its own bar. That is a real thing a percentile bootstrap can do on a
    # skewed statistic, and widening HIDES it — so it is written down here rather than left as a
    # `min`/`max` a reader would copy without noticing. On this file's data it never fires; checked
    # across all six pairs the gallery draws, the reported interval is the percentile one unchanged.
    # A project doing this for real should let the disagreement surface instead of smoothing it.
    return estimate, (min(low, estimate), max(high, estimate)), p


EFFORT_COST = (0.25, 0.35, 0.70, 1.30, 2.00, 2.60)


def effort_ladders(seed: int = 12) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Score against cost for four systems, each measured at a few effort settings.

    Not a sampled curve — five or six measured points per system, which is why the marks matter as
    much as the line joining them.
    """
    rng = np.random.default_rng(seed)
    cost = np.array(EFFORT_COST)
    ladders = {
        "System A": (cost, np.array([56.1, 58.0, 61.3, 63.2, 64.8, 64.7])),
        "System B": (cost[2:], np.array([58.2, 61.4, 61.8, 63.1])),
        "System C": (cost[1:5], np.array([50.2, 55.2, 55.7, 57.6])),
        "Baseline": (cost, np.array([40.0, 44.0, 47.0, 49.0, 50.2, 50.5])),
    }
    return {name: (x, y + rng.normal(0.0, 0.05, y.size)) for name, (x, y) in ladders.items()}


NATIONS = ("Air Nomads", "Water Tribe", "Earth Kingdom", "Fire Nation")


def bending_by_nation(seed: int = 13) -> dict[str, tuple[np.ndarray, np.ndarray, float]]:
    """Novice against master benders in each of the four nations. Entirely invented.

    Four panels of the same comparison at different strengths, which is what a grid is for: the
    Air Nomads separate cleanly, the Fire Nation barely at all.
    """
    rng = np.random.default_rng(seed)
    separations = (1.35, 0.95, 0.55, 0.12)
    p_values = (0.0002, 0.006, 0.05, 0.68)
    return {
        nation: (
            rng.normal(0.0, 1.0, 36),
            rng.normal(shift, 1.05, 48),
            p,
        )
        for nation, shift, p in zip(NATIONS, separations, p_values, strict=True)
    }


FORMATIONS = ("4-2-3-1", "3-4-3", "4-3-3", "3-5-2")
LEAGUE_AVERAGE_XG = 1.42


def expected_goals(seed: int = 14) -> tuple[np.ndarray, np.ndarray]:
    """Invented expected-goals-per-match by formation, with an asymmetric interval.

    Made-up numbers on a real quantity's scale. No season, no opponent and no player is named,
    because a fake statistic sitting beside a real name reads as a claim about that name.
    """
    rng = np.random.default_rng(seed)
    means = np.array([1.18, 1.36, 1.61, 1.74]) + rng.normal(0.0, 0.01, 4)
    errors = np.array([[0.16, 0.14, 0.13, 0.11], [0.19, 0.17, 0.15, 0.13]])
    return means, errors


STAGES_OF_THE_ROAD = (
    "The Shire",
    "Bree",
    "Moria",
    "Lothlórien",
    "Cirith Ungol",
    "Grey Havens",
)


def burden_by_stage(seed: int = 15) -> dict[str, tuple[np.ndarray, np.ndarray, float]]:
    """Two groups measured at six stages of one journey. Six panels of one comparison, all invented.

    The separations rise across the first five so a reader sees a gradient rather than six versions
    of the same picture, and the sixth is null — which is why these six stages and not six others.
    The gap between a ring-bearer and a companion grows the closer the road runs to Mordor and is
    gone at the Havens, because by then there is no Ring to carry. A grid wants a story that ends,
    and a null panel is the hardest kind to label honestly.
    """
    rng = np.random.default_rng(seed)
    separations = (0.12, 0.38, 0.62, 0.95, 1.30, 0.05)
    p_values = (0.62, 0.09, 0.02, 0.001, 0.0002, 0.81)
    return {
        state: (rng.normal(0.0, 1.0, 34), rng.normal(shift, 1.05, 46), p)
        for state, shift, p in zip(STAGES_OF_THE_ROAD, separations, p_values, strict=True)
    }


TRIALS_OF_THE_TOURNAMENT = (
    "Sword swallowing",
    "Fire breathing",
    "Plate spinning",
    "Knife juggling",
    "Lion taming",
    "Tightrope",
    "Trapeze",
    "Escapology",
    "Contortion",
    "Human cannonball",
    "Card throwing",
    "Stilt walking",
    "Hoop diving",
    "Whip cracking",
    "Unicycling",
)


def tournament_p_values(seed: int = 16) -> tuple[tuple[str, ...], list[float]]:
    """A family of fifteen tests, most of which are noise. Invented, and round on purpose.

    Eight land under 0.05 and only a few survive the correction, which is the whole reason the
    panel exists: eight stars in a table read as eight findings.
    """
    del seed  # the values are written down, not drawn
    p_values = [
        0.0004,
        0.006,
        0.011,
        0.019,
        0.028,
        0.033,
        0.041,
        0.049,
        0.08,
        0.12,
        0.19,
        0.24,
        0.41,
        0.63,
        0.88,
    ]
    return TRIALS_OF_THE_TOURNAMENT, p_values


ACTS = ("Acrobatics", "Illusion", "Clowning", "Aerials", "Beasts", "Music")
JUDGES = ("Technique", "Danger", "Showmanship", "Costume")


def act_scores(seed: int = 17) -> tuple[np.ndarray, np.ndarray]:
    """Invented judge-by-act effects and their p-values, with one act unjudged on one criterion.

    The missing cell is on purpose: a matrix panel has to say "not measured" differently from
    "measured and zero", and an example with no gap in it never shows whether it does.
    """
    rng = np.random.default_rng(seed)
    effects = rng.normal(0.0, 0.55, (len(ACTS), len(JUDGES)))
    effects[0, 0] = 1.32
    effects[4, 1] = -1.18
    effects[2, 3] = np.nan
    p_values = rng.uniform(0.0, 0.4, (len(ACTS), len(JUDGES)))
    p_values[0, 0] = 0.0003
    p_values[4, 1] = 0.004
    return effects, p_values


ROUNDS = ("Heats", "Quarter", "Semi", "Final")


def scores_by_round(seed: int = 18) -> dict[str, tuple[list[float], list[tuple[float, float]]]]:
    """Invented per-round scores with a bootstrap-style band. Round numbers, no measurement."""
    del seed
    return {
        "Acrobatics": (
            [0.10, 0.32, 0.55, 0.78],
            [(0.02, 0.18), (0.22, 0.42), (0.44, 0.66), (0.66, 0.90)],
        ),
        "Illusion": (
            [0.20, 0.28, 0.30, 0.34],
            [(0.12, 0.28), (0.19, 0.37), (0.20, 0.40), (0.23, 0.45)],
        ),
        "Beasts": (
            [0.30, 0.18, 0.02, -0.14],
            [(0.22, 0.38), (0.09, 0.27), (-0.08, 0.12), (-0.26, -0.02)],
        ),
    }


# There were TWO module-level `ARMS` until 2026-08-07, and Python does not mind: the second simply
# won, so the first one's labels were unreachable and the helper paired with them drew nothing. An
# example added against the earlier meaning would have come out mislabelled with nothing raised —
# the same shape as a `highlight` index that stays valid and quietly starts meaning something else.
ARMS = ("From scratch", "Frozen probe", "Fine-tuned", "Reference")
ARM_COLORS = ("#ED6B3B", "#2E7CE0", "#2E7CE0", "#9B3B8F")


def arm_comparison(seed: int = 19) -> dict[str, tuple[list[float], list[tuple[float, float]]]]:
    """Two metrics per arm with an interval each. Invented, round, and nobody's result.

    Shaped like a controlled head-to-head: three arms that ARE comparable and one reference that is
    not, which is why the reference stands apart on the axis and outside the backdrop.
    """
    del seed
    return {
        "Coarse score": (
            [0.42, 0.61, 0.66, 0.70],
            [(0.38, 0.46), (0.57, 0.65), (0.62, 0.70), (0.66, 0.74)],
        ),
        "Fine score": (
            [0.30, 0.52, 0.58, 0.63],
            [(0.26, 0.34), (0.48, 0.56), (0.54, 0.62), (0.59, 0.67)],
        ),
    }


# A sample rate round enough to read off the axis, and low enough that the example renders quickly.
SAMPLE_RATE = 8000


def chirped_tone(seed: int = 14) -> tuple[np.ndarray, int]:
    """An invented signal with three things a spectrogram is supposed to show, and one it is not.

    A steady tone that STOPS partway through, a rising sweep that crosses it, and a broadband click.
    Between them they exercise the three readings a time-frequency figure is for: a horizontal line
    is a constant frequency, a diagonal is a changing one, a vertical is an instant containing every
    frequency at once. The noise floor is there so the decibel floor has something to do — with a
    silent background, any floor looks like the right floor.

    Returned with its sample rate, because a spectrogram's axes are meaningless without one and
    handing back a bare array is how the two get separated.
    """
    rng = np.random.default_rng(seed)
    duration = 2.0
    t = np.arange(0.0, duration, 1.0 / SAMPLE_RATE)

    tone = np.sin(2.0 * np.pi * 600.0 * t) * (t < 1.25)  # stops at 1.25 s

    # A linear chirp, from its PHASE. Written the obvious way — `sin(2*pi * linspace(f0, f1) * t)` —
    # the instantaneous frequency is the derivative of `f(t) * t`, which is `f0 + 2*(f1-f0)*t/T`:
    # it ends at 2*f1 - f0, not at f1. With f1 = 2600 that reaches 5000 Hz on an 8 kHz signal, past
    # the 4 kHz Nyquist limit, and the sweep FOLDS BACK down the spectrogram as a mirrored line.
    # It renders as a clean bright diagonal and is an artefact of the sampling, not the signal.
    # Caught by looking at the rendered figure, which is the only place it is visible.
    start, end = 200.0, 2600.0
    phase = 2.0 * np.pi * (start * t + 0.5 * (end - start) / duration * t**2)
    sweep = 0.6 * np.sin(phase)
    click = np.zeros_like(t)
    click[int(1.6 * SAMPLE_RATE) : int(1.6 * SAMPLE_RATE) + 12] = 3.0  # one broadband instant
    noise = 0.02 * rng.standard_normal(t.size)
    return tone + sweep + click + noise, SAMPLE_RATE


def short_time_spectrum(seed: int = 14) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """The signal above as (power in dB, times, frequencies) — a plain Hann-window STFT.

    The window and hop are stated here rather than defaulted anywhere in the package, because they
    decide what the picture means: a 256-sample window at 8 kHz is 32 ms, which resolves the sweep
    in time at the cost of frequency resolution, and the opposite choice would draw a different
    figure from the same signal. That trade is the caller's, always.
    """
    from scipy.signal import ShortTimeFFT
    from scipy.signal.windows import hann

    from ogviz import to_decibels

    signal, rate = chirped_tone(seed)
    window = hann(256, sym=False)
    transform = ShortTimeFFT(window, hop=64, fs=rate, scale_to="magnitude")
    power = np.abs(transform.stft(signal)) ** 2
    return to_decibels(power, floor_db=-70.0), transform.t(signal.size), transform.f
